spring.application.name=bdcc-enset-spring-mvc
spring.datasource.url=jdbc:mysql://localhost:3307/products_db
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8084